spring:
  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/rqlcoverage"
    username: postgres
    password: postgres
