spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:5432/${DATABASE_NAME}"
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
server:
  port: 8080
